### ISSUE TITLE
How to wait until threads spawned by job are complete?

### ISSUE THREAD

**Issue by peavers** [timmolter/dropwizard-sundial#13]
If I have job with a `@SimpleTrigger` it keeps firing even with `isConcurrencyAllowed = false` before the threads of that job are complete. 

How do I go about telling the job to wait until it's spawned threads are complete before attempting to start again?

**Comment by timmolter** [comment]
sounds like I bug. I'll look into it.

**Comment by peavers** [comment]
Based on [this SO question](http://stackoverflow.com/questions/4649073/quartz-scheduler-shutdowntrue-wait-for-all-threads-started-from-running-jobs-t) (regarding Quartz) it seems to be the default action

> Quarts neither know nor cares about any threads spawned by your job

Maybe relevant? 

For the moment I've solved my issue by locking the scheduler, just not sure if that is the proper way to do it

           SundialJobScheduler.lockScheduler();
            
            if (executorService.isShutdown()) {
                SundialJobScheduler.unlockScheduler();
            }

**Comment by timmolter** [comment]
No, that's unrelated to what you're asking about it seems. `isConcurrencyAllowed = false` should not allow the job to be fired if one with the same name is still running. That's what you want, right? The S.O. thread was about spawning threads from within a Quartz/Sundial job.

**Comment by peavers** [comment]
I am spawning threads inside the job, and the job keeps trying to fire again while the threads are still running.

**Comment by timmolter** [comment]
Ah, ok. There could be a problem with that then. The S.O thread is relevant. You'll need to use the Executor trick and block at that point until the thread returns. Otherwise Quartz thinks the job is done as soon as you return from the run method.

**Comment by peavers** [comment]
Alrighty, thanks for the speedy response! :)
