### ISSUE TITLE
guice injection compatibility for jobs

### ISSUE THREAD

**Issue by gutsverwalter** [timmolter/dropwizard-sundial#2]
I've been trying to use guice injection in the sundial job, but unfortunately it doesn't work.
I am using the following guice plugin for dropwizard: https://github.com/xvik/dropwizard-guicey

Maybe you could take a look at this? 
Sorry for reporting it as a bug - didn't find any contact mail.

Thank you very much in advance!

![bildschirmfoto 2015-04-25 um 11 26 44](https://cloud.githubusercontent.com/assets/11915192/7332425/c33fad4e-eb3e-11e4-9c37-383bdbc5e648.png)

**Comment by timmolter** [comment]
No problem. Feel free to ask questions here. 

I never used guice so I cannot help you with that. If you need to access global objects inside Sundial Jobs, there is a way, which I use successfully all the time. I actually just added a section in the README about it.

https://github.com/timmolter/dropwizard-sundial/blob/master/README.md#inject-global-objects-or-config-parameters-into-a-job

If you figure out the guice injection method, I'd love to add a section to the README on how to do it if you're willing to share your findings.

**Comment by gimmebytes** [comment]
Old posting but worth the answer:

We're using the dropwizard-guice bundle in our applications and inside the jobs we inject the stuff we need like this:

```
public class SomeJob extends Job {

   @Inject
   private SomeHandler handler;

   public SomeJob () {
       Injector injector = (Injector) SundialJobScheduler.getServletContext().getAttribute(OurAwesomeContext.INJECTOR);
       injector.injectMembers(this);
   }
}
```

**Comment by peavers** [comment]
@gimmebytes I'm trying to get my head around Guice still, I don't suppose you could provide a bit more context around how you're doing this? A look at a sample Application class to match this job would be very helpful!

**Comment by saianudeepm** [comment]
The above comment helped.
Basically its two steps

1) Add the Guice injector to the app context from application class: 
 environment.getApplicationContext().setAttribute("GUICE_INJECTOR", guiceBundle.getInjector());

2) Inject members into job using this injector
public class SomeJob extends Job {

   @Inject
   private SomeHandler handler;

   public SomeJob () {
       Injector injector = (Injector) SundialJobScheduler.getServletContext().getAttribute("GUICE_INJECTOR");
       injector.injectMembers(this);
   }

@Override
    public void doRun() throws JobInterruptException {
        // Do something interesting...
    }
}

**Comment by karolmie1** [comment]
I guess it can be closed now?
