### ISSUE TITLE
Adding job manually

### ISSUE THREAD

**Issue by sheldon-sminq** [timmolter/dropwizard-sundial#3]
Hi @timmolter 

I tried to add a job manually but everytime sundial throws an exception

 SundialJobScheduler.addJob("emailJob","EmailJob");
        SundialJobScheduler.addCronTrigger("testJob", "emailJob", "23 58 12 6 4 ?");

com.xeiam.sundial.SundialJobScheduler: ERROR ADDING JOB!!!
! java.lang.ClassNotFoundException: EmailJob

**Comment by timmolter** [comment]
It should work. Should look like this:

```
SundialJobScheduler.addJob("SampleJob", "com.xeiam.sundial.jobs.SampleJob");
```

Make sure the class is on the classpath.

**Comment by timmolter** [comment]
See `SampleRun.java` in the Sundial project.
