### ISSUE TITLE
404 on Control Scheduler asynchronously via Curl

### ISSUE THREAD

**Issue by sripos** [timmolter/dropwizard-sundial#5]
Hello Tim, 

I used sundial in one of our applications successfully... however, I'm getting a 404 when I run the curl command to alter the config or to stop the scheduler.   For example, I have the applications running on port 9006 and hence the command be - 

curl -X POST "http://localhost:9006/admin/tasks/stopjob?JOB_NAME=OMIJob"

But I do not see that the job is stopped.  Also, when executed, I received a 404 on my log as follows - 

{"@timestamp":"2016-04-12T16:30:17.051-05:00","level":"ERROR","message":"Web Application Exception occurred","message_id":"71f3df1b-1fec-4a55-8512-f770d33f2e50","caller_class_name":"com.srini.soa.errors.mappers.WebAppExceptionMapper","caller_method_name":"toResponse","caller_file_name":"WebAppExceptionMapper.java","caller_line_number":26,"stack_trace":"j.w.r.NotFoundException: HTTP 404 Not Found\n\tat o.g.j.s.ServerRuntime$2.run(ServerRuntime.java:323) ~[jersey-server-2.22.1.jar:na]\n\tat o.g.j.i.Errors$1.call(Errors.java:271) [jersey-common-2.22.1.jar:na]\n\tat o.g.j.i.Errors$1.call(Errors.java:267)\n\tat o.g.j.i.Errors.process(Errors.java:315)\n\tat o.g.j.i.Errors.process(Errors.java:297)\n\tat o.g.j.i.Errors.process(Errors.java:267)\n\tat o.g.j.p.i.RequestScope.runInScope(RequestScope.java:317)\n\tat o.g.j.s.ServerRuntime.process(ServerRuntime.java:305) [jersey-server-2.22.1.jar:na]\n\tat o.g.j.s.ApplicationHandler.handle(ApplicationHandler.java:1154)\n\tat o.g.j.s.WebComponent.serviceImpl(WebComponent.java:471) [jersey-container-servlet-core-2.22.1.jar:na]\n\tat o.g.j.s.WebComponent.service(WebComponent.java:425)\n\tat o.g.j.s.ServletContainer.service(ServletContainer.java:383)\n\tat o.g.j.s.ServletContainer.service(ServletContainer.java:336)\n\tat o.g.j.s.ServletContainer.service(ServletContainer.java:223)\n\tat i.d.j.NonblockingServletHolder.handle(NonblockingServletHolder.java:49) [dropwizard-jetty-0.9.1.jar:0.9.1]\n\tat o.e.j.s.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669) [jetty-servlet-9.2.13.v20150730.jar:9.2.13.v20150730]\n\tat o.e.j.s.UserAgentFilter.doFilter(UserAgentFilter.java:83) [jetty-servlets-9.2.13.v20150730.jar:9.2.13.v20150730]\n\tat o.e.j.s.GzipFilter.doFilter(GzipFilter.java:300)\n\tat i.d.j.BiDiGzipFilter.doFilter(BiDiGzipFilter.java:132) [dropwizard-jetty-0.9.1.jar:0.9.1]\n\tat o.e.j.s.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.13.v20150730.jar:9.2.13.v20150730]\n\tat i.d.s.ThreadNameFilter.doFilter(ThreadNameFilter.java:29) [dropwizard-servlets-0.9.1.jar:0.9.1]\n\tat o.e.j.s.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.13.v20150730.jar:9.2.13.v20150730]\n\tat i.d.j.f.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:43) [dropwizard-jersey-0.9.1.jar:0.9.1]\n\tat i.d.j.f.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:38)\n\tat o.e.j.s.ServletHandler$CachedChain.doFilter(ServletHan..."}
{"@timestamp":"2016-04-12T16:30:17.052-05:00","thread_name":"dw-114","message":"HTTP Response Log Entry","message_id":"71f3df1b-1fec-4a55-8512-f770d33f2e50","http_headers":{"Content-Length":"0","Date":"Tue, 12 Apr 2016 21:30:17 GMT"},"http_status_code":404,"response_time":2}
0:0:0:0:0:0:0:1 - - [12/Apr/2016:21:30:17 +0000] "POST /admin/tasks/stopjob?JOB_NAME=OMIJob HTTP/1.1" 404 0 "-" "curl/7.43.0" 3

Do I have to explicitly implement /admin/tasks/stopjob resources?
What am I missing here? Would you know?

Thanks,
Sripos

**Comment by timmolter** [comment]
No, you shouldn't have to explicitly implement the resources. Are you adding the Sundial bundle to the Dropwizard environment properly as shown in the README?

**Comment by sripos** [comment]
Yes... it has been added... BTW, the POST command should be executed on the port (9006) on which the application is running or the admin port (9007)?

```
public void initialize(Bootstrap<PropsConfig> bootstrap) {

        bootstrap.addBundle(TenacityBundleBuilder.<PropsConfig> newBuilder().configurationFactory(new PropsExternalDependencyBundleConfigurationFactory()).build());

        bootstrap.addBundle(new SundialBundle<PropsConfig>() {

            @Override
            public SundialConfiguration getSundialConfiguration(PropsConfig configuration) {

                return configuration.getSundialConfiguration();
            }
          } );
    }
```

**Comment by sripos** [comment]
Never mind... it is working as expected... Thanks -

**Comment by timmolter** [comment]
If I run `curl -X POST "http://localhost:9090/admin/tasks/stopjob?JOB_NAME=SampleJob3"`,

I see: 

```
0:0:0:0:0:0:0:1 - - [18/Apr/2016:09:03:49 +0000] "POST /admin/tasks/stopjob?JOB_NAME=SampleJob3 HTTP/1.1" 200 - "-" "curl/7.43.0" 9
```

Take a look at https://github.com/timmolter/XDropWizard, as it's a perfectly working example. You should be using the admin port I believe.

**Comment by timmolter** [comment]
@sripos My apologies. I just noticed today that you actually do need to explicitly add the tasks in your apps `run` method like this:

```
environment.admin().addTask(new LockSundialSchedulerTask());
environment.admin().addTask(new UnlockSundialSchedulerTask());
environment.admin().addTask(new RemoveJobTriggerTask());
environment.admin().addTask(new AddCronJobTriggerTask());
environment.admin().addTask(new StartJobTask());
environment.admin().addTask(new StopJobTask());
environment.admin().addTask(new RemoveJobTask());
environment.admin().addTask(new AddJobTask());
```

I mistakenly assumed it was all taken care of automatically. From the future `1.0.0-rc2.0` release it will be automatically configured, but before that you need to explicitly add all the tasks yourself. Sorry for that! I'll update the readme as well.

**Comment by sripos** [comment]
Thanks for the response Tim, I will try to get it done today.... Thanks -
